version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - force_static_volume:/force/static
      - force_files_volume:/force/media
    networks:
      - nginx_network

volumes:
  force_static_volume:
    external: true
  force_files_volume:
    external: true
networks:
  nginx_network:
    external: true