"""
Django settings for force project.

Generated by 'django-admin startproject' using Django 3.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4&e(@j=zq$*$afilr@0w3gxs%-y$c+tg6&i4b$=_l=y7-=!0i^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 'celery',
    
    'apps.seller.apps.SellerConfig',
    'apps.accounts.apps.AccountsConfig',
    'payment',
    # 'zarinpal',
    
    'azbankgateways',
    'crispy_forms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'force.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'force.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'force_postgresql',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static/'),)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'

# ZARINPAL Config
AZ_IRANIAN_BANK_GATEWAYS = {
   'GATEWAYS': {
    #    'BMI': {
    #        'MERCHANT_CODE': '<YOUR MERCHANT CODE>',
    #        'TERMINAL_CODE': '<YOUR TERMINAL CODE>',
    #        'SECRET_KEY': '<YOUR SECRET CODE>',
    #    },
    #    'SEP': {
    #        'MERCHANT_CODE': '<YOUR MERCHANT CODE>',
    #        'TERMINAL_CODE': '<YOUR TERMINAL CODE>',
    #    },
       'ZARINPAL': {
           'MERCHANT_CODE': '5fea59ad-7f54-45a9-8799-078bd875d2a1',
           'SANDBOX': 0,  # 0 disable, 1 active
       },
    #    'IDPAY': {
    #        'MERCHANT_CODE': '<YOUR MERCHANT CODE>',
    #        'METHOD': 'POST',  # GET or POST
    #        'X_SANDBOX': 0,  # 0 disable, 1 active
    #    },
    #    'ZIBAL': {
    #        'MERCHANT_CODE': '<YOUR MERCHANT CODE>',
    #    },
    #    'BAHAMTA': {
    #        'MERCHANT_CODE': '<YOUR MERCHANT CODE>',
    #    },
    #    'MELLAT': {
    #        'TERMINAL_CODE': '<YOUR TERMINAL CODE>',
    #        'USERNAME': '<YOUR USERNAME>',
    #        'PASSWORD': '<YOUR PASSWORD>',
    #    },
   },
   'IS_SAMPLE_FORM_ENABLE': True, # اختیاری و پیش فرض غیر فعال است
   'DEFAULT': 'ZARINPAL',
   'CURRENCY': 'IRR', # اختیاری
   'TRACKING_CODE_QUERY_PARAM': 'tc', # اختیاری
   'TRACKING_CODE_LENGTH': 16, # اختیاری
   'SETTING_VALUE_READER_CLASS': 'azbankgateways.readers.DefaultReader', # اختیاری
   'BANK_PRIORITIES': [
   ], # اختیاری
}

# CACHES = {
#     'default': {
#         "BACKEND": "django_redis.cache.RedisCache",
#         'LOCATION': 'redis://127.0.0.1:6379',
        
#         "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient",},
        
#     }}

# CELERY Config
# CELERY_BROKER_URL = "redis://localhost:6379"
# CELERY_TIMEZONE = "Asia/Tehran"
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_CACHE_BACKEND = 'default'
# CELERY_RESULT_SERIALIZER = 'json'

